# Generated by cucumber-sinatra. (2016-10-07 10:20:00 -0500)

ENV['RACK_ENV'] = 'test'

require File.expand_path('../../../overlord.rb', __FILE__)

require 'capybara'
require 'capybara/cucumber'
require 'rspec'

Capybara.app = Overlord

class OverlordWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  OverlordWorld.new
end
