source 'https://rubygems.org'

gem 'haml'
gem 'sinatra'

group :development, :test do
  gem 'capybara'
  gem 'cucumber'
  gem 'cucumber-sinatra'
end

group :test do
  gem 'rspec'
  gem 'simplecov', require: false
end
